total_loss:
  - ReconLoss
  - RegLoss
  - TripletLoss
  - KLLoss
ReconLoss:
  _target_: utils.loss.ReconLoss
  weight: 0
  z_dims: False
RegLoss:
  _target_: utils.loss.RegLoss
  weight: 1
  z_dims: False
TripletLoss:
  _target_: utils.loss.TripletLoss
  weight: 150
  z_dims: False
  margin: 0.4
  p: 2
KLLoss:
  _target_: utils.loss.KLLoss
  weight: 1
  z_dims: False