encoder:
  _target_: models.Encoder
  input_size: 5 
  hidden_size: 128 
  latent_dim: 2 
  num_layers: 1 
  bidirectional: False
decoder:
  _target_: models.Decoder
  input_size: ${model.encoder.input_size}
  hidden_size: ${model.encoder.hidden_size}
  latent_dim: ${model.encoder.latent_dim}
  window_size: ${data_preprocessor.window_size}
  num_layers: 1
  bidirectional: ${model.encoder.bidirectional}
rve:
  _target_: models.RVE
  reconstruct: True
  dropout: 0.6