encoder:
  _target_: models.tshae_models.OriginalEncoder
  input_dim: 5 #21
  intermediate_dim: 300
  latent_dim: 2
decoder:
  _target_: models.tshae_models.OriginalDecoder
rve:
  _target_: models.tshae_models.OriginalRVE
  latent_dim: 2
