defaults:
  - data_preprocessor: more_sensors_FD003
  - model: base_rve
  - optimizer: adam
  - scheduler: scheduler
  - loss: triplet
  - trainer: base_trainer
  - random_seed: random_seed
  - diffusion: diffusion
  - knnmetric: knnmetric
  - noise_tester: noise_tester
  - _self_

hydra:
  sweeper:
    params:
      #random_seed.seed: 1, 5, 10, 15, 20, 25, 30, 35, 40, 42, 45, 50
      #model.encoder.dropout:  0.5
      #model.decoder.dropout_layer: 0.7
      #model.rve.dropout_regressor: 0.8
      #model.rve.regression_dims: 100
      #optimizer.lr: 0.001, 0.002, 0.005

      loss.TripletLoss.weight: 0, 25 #, 50, 75, 100, 125, 150
      #loss.ReconLoss.weight: 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2
      #optimizer.lr: 0.002, 0.003
      #model.encoder.dropout: 0.3, 0.5, 0.7, 0.8
      #model.decoder.dropout_layer: 0.3, 0.5, 0.7, 0.8
      #model.rve.dropout_regressor: 0.5, 0.7, 0.8
      #model.rve.regression_dims: 50, 100, 150
  