defaults:
  - data_preprocessor: more_sensors_FD003
  - model: base_rve
  - optimizer: adam
  - scheduler: scheduler
  - loss: triplet
  - trainer: base_trainer
  - random_seed: random_seed
  - diffusion: diffusion
  - knnmetric: knnmetric
  - noise_tester: noise_tester
  - _self_

hydra:
  sweeper:
    params:
      data_preprocessor: more_sensors_FD001, more_sensors_FD002, more_sensors_FD003, more_sensors_FD004
      random_seed.seed: 1, 2, 3, 4, 5, 6, 7, 8, 9, 42
      #optimizer.lr: 0.002, 0.003
      #model.encoder.dropout: 0.3, 0.5, 0.7, 0.8
      #model.decoder.dropout_layer: 0.3, 0.5, 0.7, 0.8
      #model.rve.dropout_regressor: 0.5, 0.7, 0.8
      #model.rve.regression_dims: 50, 100, 150
  