  dataset_name: "FD004"
  max_rul: 125
  window_size: 32
  sensors:  ['s_1', 's_2', 's_3', 's_4', 's_5', 's_6', 's_7', 's_8', 's_9', 's_10', 's_11', 's_12', 's_13', 's_14', 's_15', 's_16', 's_17', 's_18', 's_19', 's_20', 's_21']
  train_size: 0.8
  alpha: 1
  dir_path: './CMAPSSData/'
  fix_seed: ${random_seed.fix}
 
  downsample_healthy_train: False
  downsample_healthy_validation: False
  downsample_healthy_test: False
  downsample_healthy_train_p: 0
  downsample_healthy_validation_p: 0.8
  downsample_healthy_test_p: 0

  train_ds_mode: "train"
  train_ds_return_pairs: True
  train_ds_eps: 2
  train_ds_max_eps: 10
  train_ds_triplet_healthy_rul: 125

  test_ds_mode: "test"
  test_ds_return_pairs: False
  test_ds_eps: 2
  test_ds_max_eps: 10
  test_ds_triplet_healthy_rul: 125

  val_ds_mode: "train"
  val_ds_return_pairs: True
  val_ds_eps: 2
  val_ds_max_eps: 10
  val_ds_triplet_healthy_rul: 125

  train_dl_batch_size: 256
  train_dl_shuffle: True 
  train_dl_num_workers: 5

  test_dl_batch_size: 256
  test_dl_shuffle: False 
  test_dl_num_workers: 5

  val_dl_batch_size: 256
  val_dl_shuffle: True 
  val_dl_num_workers: 5